#!/usr/bin/env python3
"""gen_declarations.py — GENERATE game/declarations.h and game/declarations.json.

The world layout as the reconstructed source sees it: the three shared-
memory base pointers (SD_PTR, OBJ_PTR, CAS_PTR), the key globals, and the
record tables the P35 routines touch.  Sources: docs/GAME_REFERENCE.md
(addresses, names) + docs/Project34/Census.md §3 (strides, raw field
displacements K, the 1-based origin rule origin = minK + stride).

Field names are `f<K>` (K = the raw word displacement from the base, as
readable.py names them) unless a meaning is known.  The .h is the ONLY
game file whose C and C++ views differ (game/README.md); the .json is the
same table for compiler/translate.py, which needs the numbers, not types.

    python3 compiler/gen_declarations.py [--out game/]
"""
import argparse, hashlib, json, os, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))

# ---------------------------------------------------------------------------
# THE TABLE (hand-seeded; every row cites its source)
# ---------------------------------------------------------------------------

# static scalars: name -> (word address, width in bits, comment)
STATICS = {
    "SD_PTR":     (0x70000210, 32, "GAME_REFERENCE: player records, world state (pointer)"),
    "OBJ_PTR":    (0x70000212, 32, "GAME_REFERENCE: object/item placement data (pointer)"),
    "CAS_PTR":    (0x70000214, 32, "GAME_REFERENCE: castle data (pointer)"),
    "PLAYER_NUM": (0x70000216, 16, "GAME_REFERENCE: current player index"),
    "OUT_CHAN":   (0x70000260, 32, "GAME_REFERENCE: output channel (?WRITE_SCREEN arg 1)"),
    "IN_CHAN":    (0x70000262, 32, "GAME_REFERENCE: input channel"),
    "CITY_NUM":   (0x7000026C, 16, "GAME_REFERENCE"),
    "TERR_NUM":   (0x7000026E, 16, "GAME_REFERENCE"),
    "MOVES_LEFT": (0x70000270, 16, "GAME_REFERENCE"),
}

# direct fields through a base pointer: pointer -> {name: (K, width, comment)}
DIRECT = {
    "SD_PTR": {
        "seed":        (40, 32, "P34 Census §3: the ?RANDOM_NUMBER seed (SD_PTR->f40)"),
        "f42":         (42, 16, "P34 Census §3"),
        "player_count": (43, 16, "UPDATE_SCREENS loop bound (SD_PTR->f43.h)"),
    },
    "OBJ_PTR": {
        "region_count": (11502, 32, "P34 Census §3 / PICK_X_Y_reading: region count (OBJ_PTR->f11502)"),
    },
}

# record tables: name -> dict(base pointer, stride, minK (field 0's raw K), bound, fields{name:(K,width)})
# origin = minK + stride (P34 origin rule); element i (1-based) at base + i*stride + K.
TABLES = {
    "REGION": dict(base="OBJ_PTR", stride=9, minK=11495, bound=100000,
                   comment="P34 Census §3 OBJ_PTR_rec9; bound 100000 = PICK_X_Y's DERR 17 check",
                   fields={"x": (11495, 16), "y": (11496, 16), "type": (11497, 16),
                           "f11498": (11498, 32), "f11500": (11500, 32),
                           "f11502": (11502, 16), "f11503": (11503, 16)}),
    "PLAYER": dict(base="SD_PTR", stride=686, minK=-686 + 0, bound=10,
                   comment="P34 Census §3 SD_PTR_rec686; bound 10 = the DERR 17 check on PLAYER_NUM; "
                           "K < 0 in this table are raw displacements (origin unknown: min K seen −642)",
                   fields={"fm589": (-589, 16), "fm588": (-588, 16),
                           "screen": (-611, 32, (9, 11), (22, 2)),   # UPDATE_SCREENS: 9 rows x 11 cells of 2 words, raw K -611
                           "f19": (19, 32), "fm625": (-625, 16), "fm608": (-608, 16),
                           "fm590": (-590, 16)}),   # DIED: bit 4 of this word is the first test (bit address 16*i*686-9436)
}


def c_type(width):
    return {16: "int16_t", 32: "int32_t"}[width]


def gen_h(digest):
    L = []
    w = L.append
    w("/* declarations.h — GENERATED by compiler/gen_declarations.py; do not edit.")
    w(" * Sources: docs/GAME_REFERENCE.md + docs/Project34/Census.md §3.")
    w(" * table sha256 (of declarations.json): %s" % digest)
    w(" * This is the only game/ file whose C and C++ views differ. */")
    w("#ifndef QUEST_DECLARATIONS_H")
    w("#define QUEST_DECLARATIONS_H")
    w('#include "quest_rt.h"')
    w("")
    w("/* ---- statics (word addresses in the data segment) ---- */")
    for name, (addr, width, cmt) in STATICS.items():
        w("/* %-10s 0x%08X: %s */" % (name, addr, cmt))
    w("")
    w("/* ---- record types: fields at their raw word displacement K from the base pointer ---- */")
    for tname, t in TABLES.items():
        w("/* %s: stride %d words, 1-based origin base+%d; %s */" % (tname, t["stride"], t["minK"] + t["stride"], t["comment"]))
        w("struct %s_rec {" % tname.lower())
        # lay the fields out by K relative to minK
        for fname, spec in sorted(t["fields"].items(), key=lambda kv: kv[1][0]):
            K, width = spec[0], spec[1]
            dims = "".join("[%d]" % d for d in spec[2]) if len(spec) > 2 else ""
            w("    %s %s%s;   /* K=%d%s */" % (c_type(width), fname, dims, K,
                                             ", row strides %s words" % list(spec[3]) if dims else ""))
        w("};")
    for pname, fields in DIRECT.items():
        w("struct %s_hdr {" % pname.lower())
        for fname, (K, width, cmt) in sorted(fields.items(), key=lambda kv: kv[1][0]):
            w("    %s %s;   /* K=%d: %s */" % (c_type(width), fname, K, cmt))
        w("};")
    w("")
    w("#ifdef __cplusplus")
    w("/* C++ view: real objects bound to the world image (native runtime, later). */")
    for name, (addr, width, cmt) in STATICS.items():
        if name in DIRECT:
            w("extern based_ptr<struct %s_hdr> %s;   /* 0x%08X */" % (name.lower(), name, addr))
        elif name.endswith("_PTR"):
            w("extern based_ptr<void> %s;   /* 0x%08X */" % (name, addr))
        else:
            w("extern %s %s;   /* 0x%08X */" % (c_type(width), name, addr))
    for tname, t in TABLES.items():
        w("extern ARRAY1(struct %s_rec, %d) %s;   /* via %s, origin +%d */" % (
            tname.lower(), t["bound"], tname, t["base"], t["minK"] + t["stride"]))
    w("#else")
    w("/* C view (pycparser / the translator): plain declarations; the numbers live in declarations.json. */")
    for name, (addr, width, cmt) in STATICS.items():
        if name in DIRECT:
            w("extern struct %s_hdr *%s;   /* 0x%08X */" % (name.lower(), name, addr))
        elif name.endswith("_PTR"):
            w("extern void *%s;   /* 0x%08X */" % (name, addr))
        else:
            w("extern %s %s;   /* 0x%08X */" % (c_type(width), name, addr))
    for tname, t in TABLES.items():
        w("extern struct %s_rec %s[%d];   /* via %s, 1-based, origin +%d */" % (
            tname.lower(), tname, t["bound"], t["base"], t["minK"] + t["stride"]))
    w("#endif")
    w("#endif")
    return "\n".join(x for x in L if x is not None) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "game"))
    args = ap.parse_args()
    table = dict(statics={n: dict(addr=a, width=w, comment=c) for n, (a, w, c) in STATICS.items()},
                 direct={p: {n: dict(K=k, width=w, comment=c) for n, (k, w, c) in f.items()} for p, f in DIRECT.items()},
                 tables={n: dict(base=t["base"], stride=t["stride"], minK=t["minK"], origin=t["minK"] + t["stride"],
                                 bound=t["bound"], comment=t["comment"],
                                 fields={fn: dict(K=sp[0], width=sp[1], **({"dims": list(sp[2]), "strides": list(sp[3])} if len(sp) > 2 else {}))
                                         for fn, sp in t["fields"].items()})
                         for n, t in TABLES.items()})
    js = json.dumps(table, indent=1, sort_keys=True)
    digest = hashlib.sha256(js.encode()).hexdigest()[:16]
    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, "declarations.json"), "w") as f:
        f.write(js + "\n")
    with open(os.path.join(args.out, "declarations.h"), "w") as f:
        f.write(gen_h(digest))
    print("wrote declarations.h / declarations.json (table %s)" % digest)


if __name__ == "__main__":
    main()
