#!/usr/bin/env python3
"""tools/arena.py — generate quest.arena, the P33-B arena layout: one temp
per WMSP claim (s@<block>.<k>, 57), at a fixed word address in the arena
segment [0x75000000, 0x75800000), with a capacity in bytes.

Input: quest.strhooks (rows + wmsp lines with the census size expressions).
Capacity: a constant claim size is bounded exactly (cap = 4·size bytes,
bound=exact); a symbolic size (lengths of varyings whose declared
capacities the census does not carry — arg strings, record fields) gets
the PROVISIONAL 8192 bytes (bound=unbounded, the expression recorded).
The runtime `claim s@b.k, acN` statement asserts 4·acN <= cap on every
execution, so an undersized capacity is a loud fault, never silent
overflow; the battery's per-temp max-claim counters size the final column.

Stride 0x2000 words per temp: a row's extent is 1 + cap/2 words plus the
closed right end (Mapper I1), so 8192-byte temps need more than 0x1000.

Usage: arena.py --strhooks quest.strhooks --out quest.arena
"""
import argparse, hashlib, re

ARENA_BASE = 0x75000000
STRIDE = 0x2000            # words (a twin's extent is 1 + cap/2 words plus the closed right end)
PROVISIONAL = 8192         # bytes


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--strhooks', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    rows = {}
    temps = []
    for line in open(a.strhooks):
        t = line.split()
        if line.startswith('row '):
            rows[int(t[1])] = {'block': t[2], 'routine': t[3]}
        elif line.startswith('wmsp '):
            pc = t[1]; rid = int(t[2].split('=')[1]); n = int(t[3].split('=')[1])
            size = line.split('size=', 1)[1].strip()
            temps.append((rid, n, pc, size))
    temps.sort()
    sha = hashlib.sha256(open(a.strhooks, 'rb').read()).hexdigest()[:16]
    out = ['# quest.arena — P33-B arena layout: one twin per WMSP claim, s@<block>.<k> (docs/Project33/REPORT-B.md)',
           f'# generated by tools/arena.py from quest.strhooks sha256 {sha}',
           f'# temps {len(temps)}  base 0x{ARENA_BASE:08X}  stride 0x{STRIDE:X} words  provisional capacity {PROVISIONAL} bytes',
           '# temp <id> s@<block>.<k> arena=<word addr> cap=<bytes> bound=<exact|unbounded> wmsp=<pc> routine=<r> size=<census wides expr>']
    for i, (rid, n, pc, size) in enumerate(temps, 1):
        blk = rows[rid]['block']
        addr = ARENA_BASE + (i - 1) * STRIDE
        if re.fullmatch(r'\d+', size):
            cap, bound = 4 * int(size), 'exact'
        else:
            cap, bound = PROVISIONAL, 'unbounded'
        out.append(f'temp {i} s@{blk}.{n} arena={addr:08X} cap={cap} bound={bound} wmsp={pc} routine={rows[rid]["routine"]} size={size}')
    open(a.out, 'w').write('\n'.join(out) + '\n')
    print(f'arena: {len(temps)} temps -> {a.out}')


if __name__ == '__main__':
    main()
