/* declarations.h — GENERATED by compiler/gen_declarations.py; do not edit.
 * Sources: docs/GAME_REFERENCE.md + docs/Project34/Census.md §3.
 * table sha256 (of declarations.json): d094c5426847485e
 * This is the only game/ file whose C and C++ views differ. */
#ifndef QUEST_DECLARATIONS_H
#define QUEST_DECLARATIONS_H
#include "quest_rt.h"

/* ---- statics (word addresses in the data segment) ---- */
/* SD_PTR     0x70000210: GAME_REFERENCE: player records, world state (pointer) */
/* OBJ_PTR    0x70000212: GAME_REFERENCE: object/item placement data (pointer) */
/* CAS_PTR    0x70000214: GAME_REFERENCE: castle data (pointer) */
/* PLAYER_NUM 0x70000216: GAME_REFERENCE: current player index */
/* OUT_CHAN   0x70000260: GAME_REFERENCE: output channel (?WRITE_SCREEN arg 1) */
/* IN_CHAN    0x70000262: GAME_REFERENCE: input channel */
/* CITY_NUM   0x7000026C: GAME_REFERENCE */
/* TERR_NUM   0x7000026E: GAME_REFERENCE */
/* MOVES_LEFT 0x70000270: GAME_REFERENCE */

/* ---- record types: fields at their raw word displacement K from the base pointer ---- */
/* REGION: stride 9 words, 1-based origin base+11504; P34 Census §3 OBJ_PTR_rec9; bound 100000 = PICK_X_Y's DERR 17 check */
struct region_rec {
    int16_t x;   /* K=11495 */
    int16_t y;   /* K=11496 */
    int16_t type;   /* K=11497 */
    int32_t f11498;   /* K=11498 */
    int32_t f11500;   /* K=11500 */
    int16_t f11502;   /* K=11502 */
    int16_t f11503;   /* K=11503 */
};
/* PLAYER: stride 686 words, 1-based origin base+0; P34 Census §3 SD_PTR_rec686; bound 10 = the DERR 17 check on PLAYER_NUM; K < 0 in this table are raw displacements (origin unknown: min K seen −642) */
struct player_rec {
    int16_t fm625;   /* K=-625 */
    int32_t screen[9][11];   /* K=-611, row strides [22, 2] words */
    int16_t fm608;   /* K=-608 */
    int16_t fm591;   /* K=-591 */
    int16_t fm590;   /* K=-590 */
    int16_t fm589;   /* K=-589 */
    int16_t fm588;   /* K=-588 */
    int16_t fm390[10];   /* K=-390, row strides [1] words */
    int32_t f19;   /* K=19 */
};
struct sd_ptr_hdr {
    int32_t seed;   /* K=40: P34 Census §3: the ?RANDOM_NUMBER seed (SD_PTR->f40) */
    int16_t f42;   /* K=42: P34 Census §3 */
    int16_t player_count;   /* K=43: UPDATE_SCREENS loop bound (SD_PTR->f43.h) */
};
struct obj_ptr_hdr {
    int32_t region_count;   /* K=11502: P34 Census §3 / PICK_X_Y_reading: region count (OBJ_PTR->f11502) */
};

/* ---- parent frames: the static link's targets (P39) ----
 * A nested procedure's UPLINK(P) points at one of these.  Members are at
 * their WORD displacement off the parent's frame pointer; `__aK` is the
 * parent's K'th argument (by reference, at wfp-10-2K).
 *
 * This view NAMES the slots and type-checks uses; it does NOT reproduce
 * the frame's layout, and nothing should read offsetof() from it.  It
 * cannot: the arguments sit at NEGATIVE displacements (wfp-10-2K) and the
 * locals at positive ones, so no single struct puts both in address
 * order.  The translator does not read this struct — it reads the same
 * table from declarations.json, where the slot numbers are exact. */
struct LIST_PLAYERS__frame {
    int16_t __pad13[13];
    int16_t w13;   /* wp(link, 13) — LIST_PLAYERS.3@7016F59F: XNLDA 1,[ac2+0xD] — compared against PLAYER(i).fm629 */
};
struct FIRE__frame {
    int16_t *__a1;   /* the parent's argument 1, at wfp-12 — FIRE.2@7016A479: XNLDA 1,@[ac2+0xFFF4] — a PLAYER subscript (DERR 17 bound 10) */
    void *__a2;   /* the parent's argument 2, at wfp-14 — width not witnessed yet */
    int16_t __pad10[10];
    int32_t w10;   /* wp(link, 10) — FIRE.1@7016A3C0: XWLDA 0,[ac2+0xA]; a REGION subscript (DERR 17 bound 100000) */
    int32_t w12;   /* wp(link, 12) — FIRE.2@7016A483: XWLDA 0,[ac2+0xC]; a PLAYER subscript (DERR 17 bound 10) */
    int32_t w14;   /* wp(link, 14) — FIRE.1@7016A3DA: XWSTA 0,[ac3+0xE] — WRITTEN uplevel, and read back at 7016A401 */
};

#ifdef __cplusplus
/* C++ view: real objects bound to the world image (native runtime, later). */
extern based_ptr<struct sd_ptr_hdr> SD_PTR;   /* 0x70000210 */
extern based_ptr<struct obj_ptr_hdr> OBJ_PTR;   /* 0x70000212 */
extern based_ptr<void> CAS_PTR;   /* 0x70000214 */
extern int16_t PLAYER_NUM;   /* 0x70000216 */
extern int32_t OUT_CHAN;   /* 0x70000260 */
extern int32_t IN_CHAN;   /* 0x70000262 */
extern int16_t CITY_NUM;   /* 0x7000026C */
extern int16_t TERR_NUM;   /* 0x7000026E */
extern int16_t MOVES_LEFT;   /* 0x70000270 */
extern ARRAY1(struct region_rec, 100000) REGION;   /* via OBJ_PTR, origin +11504 */
extern ARRAY1(struct player_rec, 10) PLAYER;   /* via SD_PTR, origin +0 */
#else
/* C view (pycparser / the translator): plain declarations; the numbers live in declarations.json. */
extern struct sd_ptr_hdr *SD_PTR;   /* 0x70000210 */
extern struct obj_ptr_hdr *OBJ_PTR;   /* 0x70000212 */
extern void *CAS_PTR;   /* 0x70000214 */
extern int16_t PLAYER_NUM;   /* 0x70000216 */
extern int32_t OUT_CHAN;   /* 0x70000260 */
extern int32_t IN_CHAN;   /* 0x70000262 */
extern int16_t CITY_NUM;   /* 0x7000026C */
extern int16_t TERR_NUM;   /* 0x7000026E */
extern int16_t MOVES_LEFT;   /* 0x70000270 */
extern struct region_rec REGION[100000];   /* via OBJ_PTR, 1-based, origin +11504 */
extern struct player_rec PLAYER[10];   /* via SD_PTR, 1-based, origin +0 */
#endif
#endif
